name: Build StarlightGUI

# 支持手动触发
on:
  workflow_dispatch:

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.1

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore NuGet packages
        run: nuget restore StarlightGUI.sln

      - name: Build solution
        run: msbuild StarlightGUI.sln /p:Configuration=Release /p:Platform=x64

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: StarlightGUI-Build
          path: |
            **\Release\*
